2025-03-26 17:35:53,037 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-26 17:35:54,333 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-26 17:35:55,302 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-26 17:35:55,721 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-26 17:35:57,985 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-26 17:35:58,037 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-26 17:35:58,037 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
2025-03-26 17:47:48,099 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-26 17:47:49,268 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-26 17:47:50,146 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-26 17:47:50,543 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-26 17:47:52,690 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-26 17:47:52,742 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-26 17:47:52,742 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
2025-03-26 18:21:15,804 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-26 18:21:17,086 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-26 18:21:18,065 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-26 18:21:18,500 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-26 18:21:21,018 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-26 18:21:21,074 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-26 18:21:21,075 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
2025-03-27 08:06:57,395 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-27 08:06:58,673 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-27 08:06:59,712 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-27 08:07:00,183 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-27 08:07:02,794 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-27 08:07:02,872 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-27 08:07:02,872 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
2025-03-27 08:22:53,919 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-27 08:22:55,079 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-27 08:22:56,018 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-27 08:22:56,405 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-27 08:22:58,563 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-27 08:22:58,615 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-27 08:22:58,615 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
2025-03-27 08:25:47,730 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5403497 Parameters
2025-03-27 08:25:48,881 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 5699529 Parameters
2025-03-27 08:25:49,808 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1896395 Parameters
2025-03-27 08:25:50,209 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1230943 Parameters
2025-03-27 08:25:52,685 - pynas.core.population - ERROR - Error encountered when checking individual: Model size is too big: 1677555 Parameters
2025-03-27 08:25:52,742 - pynas.core.population - INFO - Population saved to ./models_traced/src/population_0.pkl
2025-03-27 08:25:52,743 - pynas.core.population - INFO - DataFrame saved to ./models_traced/src/df_population_0.pkl
